create or replace PROCEDURE createUsers
(
    FNAME in VARCHAR2,
LNAME in VARCHAR2,
ADDRESS_1 in VARCHAR2,
ADDRESS_2 in VARCHAR2,
CITY in VARCHAR2,
STATE in VARCHAR2,
ZIPCODE in VARCHAR2,
PHONE in VARCHAR2,
SPECC in VARCHAR2,
EMAIL in VARCHAR2,
PSWD in VARCHAR2,
ROLE_ID in NUMBER,
IS_ACTIVE in BINARY_DOUBLE
)

is 
empId number default EMPLOYEESEQUENCE.nextval;
begin 
   insert into employee values (empId, FNAME, LNAME, ADDRESS_1, ADDRESS_2, CITY, STATE, ZIPCODE, PHONE, SPECC, EMAIL, PSWD, ROLE_ID, IS_ACTIVE);
end;
/